import { useShallow } from "zustand/react/shallow";
import { useStore } from "../../../store/useStore";

export function usePOSStore() {
  return useStore(useShallow((state) => ({
    products: state.products,
    cart: state.cart,
    addToCart: state.addToCart,
    updateCartQty: state.updateCartQty,
    clearCart: state.clearCart,
    processTransaction: state.processTransaction,
    branches: state.branches,
    currentBranchId: state.currentBranchId,
    setCurrentBranch: state.setCurrentBranch,
    activeSessionId: state.activeSessionId,
    setActiveSessionId: state.setActiveSessionId,
    currencies: state.currencies,
    getBaseCurrency: state.getBaseCurrency,
    currentCustomerId: state.currentCustomerId,
    setCartCustomer: state.setCartCustomer,
    currentUser: state.currentUser,
    pendingOrders: state.pendingOrders,
    removePendingOrder: state.removePendingOrder,
    getCurrentSession: state.getCurrentSession,
    openSession: state.openSession,
    closeSession: state.closeSession,
    addCashMovement: state.addCashMovement,
    removeCashMovement: state.removeCashMovement,
    inventory: state.inventory,
    addCustomer: state.addCustomer,
    bankCards: state.bankCards,
    addBankTransaction: state.addBankTransaction,
    customers: state.customers,
    users: state.users,
    logout: state.logout,
    createReturn: state.createReturn,
    processReturn: state.processReturn,
    receiptConfig: state.receiptConfig,
    addNotification: state.addNotification,
    joinOpenSession: state.joinOpenSession,
    salarySettlements: state.salarySettlements,
  })));
}
