import type { User } from "../../types";

export type PalmiTourStep = {
  id: string;
  path?: string;
  navSelector?: string;
  selector?: string;
  eyebrow: string;
  title: string;
  actionTitle?: string;
  actionMessage?: string;
  message: string;
  tip?: string;
  permission?: string;
  requiresAction?: boolean;
};

const nav = (path: string) => `[data-palmi-nav="${path}"]`;

export const PALMI_TOUR_STEPS: PalmiTourStep[] = [
  { id:"welcome", eyebrow:"Guía interactiva PALMYRA", title:"Soy Palmi", actionTitle:"Empezamos juntos", actionMessage:"Yo te indico el camino y tú haces cada paso dentro de PALMYRA. No voy a abrir las secciones por ti: quiero que aprendas dónde está cada cosa.", message:"En cada área te explicaré qué es, qué debes mirar y cómo encaja con el resto del negocio. Puedes pausar, cerrar o volver a empezar cuando quieras.", tip:"Tu ritmo manda. Palmi no modifica datos ni ejecuta operaciones por ti." },
  { id:"dashboard", path:"/", navSelector:nav("/"), selector:"main h2", eyebrow:"01 · Tu punto de partida", title:"Dashboard", actionTitle:"Tu turno", actionMessage:"Busca «Dashboard» en el menú lateral y presiónalo. Cuando entres, te mostraré qué información es importante aquí.", message:"Perfecto. Este es tu centro de mando: aquí ves una lectura rápida de ventas, tickets, stock y clientes. Úsalo para entender cómo está el negocio antes de entrar a una operación.", tip:"Mira tendencias y alertas; no necesitas memorizar todas las cifras.", permission:"reports.view", requiresAction:true },
  { id:"pos", path:"/pos", navSelector:nav("/pos"), selector:"main h3", eyebrow:"02 · Operación diaria", title:"Punto de Venta", actionTitle:"Vamos a la caja", actionMessage:"Busca «Punto de Venta» en el menú y ábrelo. No cobres nada todavía; solo entra para reconocer el espacio.", message:"Aquí ocurre la operación de venta: catálogo, carrito, cobro, vendedor, caja, impresión y continuidad offline. Primero aprende el espacio; después podrás practicar.", tip:"Antes de vender, confirma el almacén y el turno de caja que estás usando.", permission:"pos.access", requiresAction:true },
  { id:"transfers", path:"/transfers", navSelector:nav("/transfers"), selector:"main h2", eyebrow:"03 · Logística", title:"Transferencias", actionTitle:"Mueve mercancía con control", actionMessage:"Busca «Transferencias» en el menú lateral y ábrelo. Vamos a reconocer la sección antes de hacer cualquier traslado.", message:"Aquí organizas el movimiento de mercancía entre almacenes. Revisa origen, destino e historial sin mezclar este proceso con la venta.", tip:"Palmi nunca ejecutará un traslado durante el recorrido.", permission:"inventory.manage", requiresAction:true },
  { id:"customers", path:"/customers", navSelector:nav("/customers"), selector:"main h2", eyebrow:"04 · Relación con clientes", title:"Clientes", actionTitle:"Abre Clientes", actionMessage:"Busca «Clientes (POS)» en el menú y presiónalo. Al entrar, fíjate en el buscador y el directorio.", message:"Aquí mantienes el directorio de clientes y su historial. Esta información complementa la venta y ayuda a reconocer a quién estás atendiendo.", tip:"El buscador está pensado para trabajar rápido desde tablet o teléfono.", permission:"customers.manage", requiresAction:true },
  { id:"inventory", path:"/inventory", navSelector:nav("/inventory"), selector:"main h2", eyebrow:"05 · Control de stock", title:"Inventario", actionTitle:"Abre Inventario", actionMessage:"Busca «Inventario» en el menú y ábrelo. No edites productos todavía; primero reconoce las áreas de control.", message:"Aquí controlas productos, existencias, precios, categorías, etiquetas y movimientos. Es la fuente de verdad operativa de lo que tienes disponible.", tip:"Trabaja siempre con el almacén correcto antes de ajustar cantidades.", permission:"inventory.manage", requiresAction:true },
  { id:"inventory-audit", path:"/inventory-audit", navSelector:nav("/inventory-audit"), selector:"main h2, main h1, main h3", eyebrow:"06 · Verificación", title:"Auditoría de Stock", actionTitle:"Comprobemos el stock", actionMessage:"Busca «Auditoría Stock» y ábrela. Aquí aprenderás dónde verificar diferencias físicas.", message:"Esta sección sirve para comparar lo registrado con lo que realmente existe. Es una capa de control para detectar diferencias antes de tomar decisiones sobre inventario.", tip:"Una auditoría bien hecha documenta diferencias; no las oculta.", permission:"inventory.manage", requiresAction:true },
  { id:"suppliers", path:"/suppliers", navSelector:nav("/suppliers"), selector:"main h1", eyebrow:"07 · Abastecimiento", title:"Proveedores", actionTitle:"Abre Proveedores", actionMessage:"Busca «Proveedores» en el menú y presiónalo. Fíjate en el directorio y las órdenes de compra.", message:"Aquí organizas proveedores y abastecimiento. Comprar y vender son procesos distintos, pero quedan conectados por la información del negocio.", tip:"Mantén los datos del proveedor claros para conservar un historial útil.", permission:"suppliers.manage", requiresAction:true },
  { id:"banks", path:"/banks", navSelector:nav("/banks"), selector:"main h1", eyebrow:"08 · Finanzas", title:"Cuentas Bancarias", actionTitle:"Abre Finanzas", actionMessage:"Busca «Cuentas Bancarias» en el menú y ábrela. Vamos a ubicar las cuentas y movimientos.", message:"Aquí controlas cuentas, tarjetas y movimientos bancarios de la operación administrativa. La cuenta bancaria y la caja de efectivo no son lo mismo.", tip:"Revisa siempre la cuenta correcta antes de registrar un movimiento.", permission:"settings.manage", requiresAction:true },
  { id:"returns", path:"/returns", navSelector:nav("/returns"), selector:"main h2", eyebrow:"09 · Postventa", title:"Devoluciones", actionTitle:"Abre Devoluciones", actionMessage:"Busca «Devoluciones» y entra. Solo vamos a conocer el flujo; no crearemos ninguna devolución.", message:"Aquí gestionas operaciones de postventa y mantienes su trazabilidad. La información queda vinculada al historial de ventas.", tip:"Una devolución correcta debe poder explicarse después: qué pasó, cuándo y sobre qué venta.", permission:"pos.access", requiresAction:true },
  { id:"reports", path:"/reports", navSelector:nav("/reports"), selector:"main h1, main h2, main h3", eyebrow:"10 · Decisiones", title:"Reportes", actionTitle:"Abre Reportes", actionMessage:"Busca «Reportes» en el menú y presiónalo. Cuando cargue, fíjate en los bloques de resultados.", message:"Aquí conviertes la operación diaria en información para decidir: ventas, caja, inventario, trabajadores y resultados.", tip:"Los reportes cuentan lo que pasó; las secciones operativas cambian lo que ocurrirá.", permission:"reports.view", requiresAction:true },
  { id:"team", path:"/team", navSelector:nav("/team"), selector:"main h1, main h2", eyebrow:"11 · Personas", title:"Equipo", actionTitle:"Abre Equipo", actionMessage:"Busca «Equipo» en el menú y ábrelo. Esta será tu única vista para crear y administrar trabajadores.", message:"Aquí administras trabajador, código, salario, rol, almacenes y acceso web. Todo queda en un solo flujo para evitar duplicar información.", tip:"Configuración ya no es el lugar para crear empleados: usa Equipo.", permission:"employees.manage", requiresAction:true },
  { id:"settings", path:"/settings", navSelector:nav("/settings"), selector:"main h2", eyebrow:"12 · Sistema", title:"Configuración", actionTitle:"Abre Configuración", actionMessage:"Busca «Configuración» en el menú y presiónala. Aquí aprenderás dónde se ajusta la empresa y el funcionamiento general.", message:"Aquí personalizas empresa, almacenes, monedas, impresión, conectividad, apariencia y opciones avanzadas. La administración de trabajadores permanece en Equipo.", tip:"Configuración define el sistema; Equipo define las personas.", permission:"settings.manage", requiresAction:true },
  { id:"subscription", path:"/subscription", navSelector:nav("/subscription"), selector:"main h1", eyebrow:"13 · Plan", title:"Facturación y plan", actionTitle:"Revisa tu plan", actionMessage:"Busca «Plan» en el menú y ábrelo. Solo revisaremos el estado y los límites, sin cambiar nada.", message:"Aquí ves el plan de la empresa, límites y estado de la suscripción. Esta información ayuda a saber qué capacidad tiene tu espacio.", tip:"Revisa los límites antes de ampliar la operación.", permission:"settings.manage", requiresAction:true },
  { id:"security", path:"/security", selector:"main h1", eyebrow:"14 · Seguridad", title:"Dispositivos y sesiones", actionTitle:"Revisa Seguridad", actionMessage:"Cuando «Seguridad» esté disponible para tu perfil, ábrela desde el menú y revisa los dispositivos y sesiones.", message:"Aquí controlas sesiones y dispositivos autorizados. Es una capa administrativa para proteger el acceso a la empresa.", tip:"Nunca compartas las credenciales del propietario con un trabajador.", permission:"security.manage", requiresAction:false },
  { id:"offline", path:"/", navSelector:nav("/"), selector:'[data-tour="offline-status"]', eyebrow:"15 · Continuidad", title:"Modo Offline", actionTitle:"Volvamos a la operación", actionMessage:"Regresa al Dashboard desde el menú. Luego mira el indicador de conexión de PALMYRA en la zona inferior del panel.", message:"Ese indicador te dice si PALMYRA está online u offline y cuántas operaciones esperan sincronización. Las operaciones pendientes deben conservarse hasta poder sincronizarse.", tip:"No borres la cola offline para intentar recuperar una operación.", requiresAction:true },
  { id:"finish", eyebrow:"Recorrido completado", title:"Ahora ya sabes dónde trabajar", message:"Has recorrido la estructura principal de PALMYRA. Desde aquí, Palmi queda como ayuda contextual y puedes repetir el recorrido cuando quieras.", tip:"Aprende el camino primero; después podrás trabajar cada sección con mucha más seguridad." }
];

export function getAccessiblePalmiTourSteps(currentUser: Pick<User, "role" | "permissions"> | null | undefined) {
  const isAdmin = currentUser?.role === "admin";
  return PALMI_TOUR_STEPS.filter(step => !step.permission || isAdmin || currentUser?.permissions?.includes(step.permission));
}