import React from "react";
import {ArrowRight, BarChart3, Boxes, Check, ChevronRight, CloudOff, CreditCard, MonitorSmartphone, PackageCheck, Users, WifiOff, Zap} from "lucide-react";
import {useNavigate} from "react-router-dom";

const plans=[
 {name:"Starter",price:"10",badge:"90 días gratis",features:["1 almacén","Hasta 2 empleados","Hasta 50 productos","POS completo","Clientes y proveedores","Reportes básicos","Modo offline"]},
 {name:"Growth",price:"15",badge:"Para negocios en crecimiento",features:["Hasta 3 almacenes","Hasta 4 empleados","Hasta 150 productos","POS completo","Transferencias","Compras y proveedores","Reportes avanzados","Modo offline"]},
 {name:"Pro",price:"25",badge:"Máxima capacidad",features:["Hasta 7 almacenes","Hasta 10 empleados","Hasta 300 productos","POS completo","Transferencias","Compras y proveedores","Reportes avanzados+","Analítica avanzada","Soporte prioritario"]}
];
const features=[
 {icon:MonitorSmartphone,title:"Desde cualquier dispositivo",text:"Tu equipo puede trabajar desde PC, tablet o teléfono con su propia cuenta y permisos."},
 {icon:Boxes,title:"Inventario y almacenes",text:"Controla existencias y movimientos sin perder de vista dónde está cada producto."},
 {icon:CreditCard,title:"Caja y POS",text:"Ventas, turnos, pagos, devoluciones y cierres en un flujo sencillo."},
 {icon:CloudOff,title:"Offline de verdad",text:"Continúa trabajando con conexión inestable y sincroniza cuando internet regrese."},
 {icon:Users,title:"Equipo y permisos",text:"Cada trabajador entra con su cuenta y solo ve lo que su rol permite."},
 {icon:BarChart3,title:"Reportes",text:"Convierte las operaciones diarias en información útil para decidir mejor."}
];
export default function LandingPage(){
 const navigate=useNavigate();
 return <div className="palmyra-landing-page min-h-screen bg-[#FAF9FF] text-[#171522]">
  <header className="sticky top-0 z-40 border-b border-violet-100/80 bg-[#FAF9FF]/95"><div className="max-w-7xl mx-auto px-5 sm:px-8 h-16 flex items-center justify-between"><button onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} className="flex items-center gap-2.5"><span className="w-9 h-9 rounded-xl bg-violet-600 text-white flex items-center justify-center"><Zap className="w-5 h-5"/></span><span className="font-black tracking-tight text-lg">PALMYRA</span></button><nav className="hidden md:flex items-center gap-7 text-sm font-bold text-slate-600"><a href="#caracteristicas">Características</a><a href="#planes">Planes</a><a href="#como-funciona">Cómo funciona</a></nav><div className="flex items-center gap-2"><button onClick={()=>navigate("/auth")} className="hidden sm:block px-4 py-2 text-sm font-black text-violet-700">Entrar</button><button onClick={()=>navigate("/auth?mode=signup")} className="px-4 py-2.5 rounded-xl bg-violet-600 text-white text-sm font-black">Crear cuenta</button></div></div></header>
  <main>
   <section className="relative overflow-hidden"><div className="absolute -top-32 -right-32 w-96 h-96 rounded-full bg-violet-200/50 blur-3xl"/><div className="max-w-7xl mx-auto px-5 sm:px-8 pt-20 pb-16 lg:pt-28 lg:pb-24 grid lg:grid-cols-[1.08fr_.92fr] gap-14 items-center"><div><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-violet-100 text-violet-700 text-xs font-black"><span className="w-1.5 h-1.5 rounded-full bg-violet-600"/>Gestión empresarial simple y profesional</div><h1 className="text-5xl sm:text-6xl lg:text-7xl font-black tracking-tight leading-[.98] mt-6">Tu negocio,<br/><span className="text-violet-600">bajo control.</span></h1><p className="text-lg sm:text-xl text-slate-600 leading-8 mt-7 max-w-2xl">PALMYRA reúne ventas, inventario, caja, compras, clientes, empleados, almacenes y reportes en un solo sistema diseñado para trabajar incluso cuando internet falla.</p><div className="flex flex-col sm:flex-row gap-3 mt-8"><button onClick={()=>navigate("/auth?mode=signup")} className="h-13 px-6 rounded-2xl bg-violet-600 text-white font-black flex items-center justify-center gap-2">Crear mi cuenta <ArrowRight className="w-4 h-4"/></button><a href="#planes" className="h-13 px-6 rounded-2xl bg-white border border-violet-200 text-violet-700 font-black flex items-center justify-center">Ver planes</a></div><div className="flex flex-wrap gap-5 mt-7 text-xs font-bold text-slate-500"><span className="flex items-center gap-1.5"><Check className="w-4 h-4 text-emerald-600"/>Starter con 90 días gratis</span><span className="flex items-center gap-1.5"><Check className="w-4 h-4 text-emerald-600"/>Modo offline</span></div></div>
   <div className="relative"><div className="rounded-[2rem] border border-violet-200 bg-white shadow-2xl p-3 rotate-[1deg]"><div className="rounded-[1.5rem] bg-[#171128] overflow-hidden"><div className="h-9 border-b border-white/10 flex items-center px-4 gap-1.5"><span className="w-2.5 h-2.5 rounded-full bg-white/20"/><span className="w-2.5 h-2.5 rounded-full bg-white/20"/><span className="w-2.5 h-2.5 rounded-full bg-white/20"/><span className="ml-auto text-[9px] text-white/50">PALMYRA</span></div><div className="p-5 grid grid-cols-2 gap-3"><div className="col-span-2 rounded-2xl bg-violet-600 p-5 text-white"><p className="text-xs font-bold text-violet-100">Ventas de hoy</p><p className="text-3xl font-black mt-2">$ 2,845</p><div className="mt-4 h-10 flex items-end gap-1">{[32,46,38,60,52,70,64,84,76,92].map((h,i)=><span key={i} style={{height:h+"%"}} className="flex-1 rounded-t bg-white/35"/>)}</div></div>{["Inventario","Caja","Empleados","Reportes"].map((x,i)=><div key={x} className="rounded-2xl bg-white/7 border border-white/8 p-4"><p className="text-[10px] text-white/50">{x}</p><p className="text-lg font-black text-white mt-2">{["1,248","$ 845","8","Hoy"][i]}</p></div>)}</div></div></div><div className="absolute -bottom-5 -left-5 rounded-2xl bg-white border border-violet-100 shadow-xl px-4 py-3 flex items-center gap-3"><span className="w-9 h-9 rounded-xl bg-emerald-100 text-emerald-700 flex items-center justify-center"><WifiOff className="w-4 h-4"/></span><div><p className="text-[10px] font-black">Modo offline</p><p className="text-[9px] text-slate-500">Trabaja sin conexión</p></div></div></div></div></section>
   <section id="caracteristicas" className="bg-white border-y border-slate-100"><div className="max-w-7xl mx-auto px-5 sm:px-8 py-20"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.2em] text-violet-600">Todo en un solo lugar</p><h2 className="text-3xl sm:text-4xl font-black mt-3 tracking-tight">Potente por dentro.<br/>Fácil para tu equipo.</h2><p className="text-slate-600 mt-4 leading-7">PALMYRA está pensado para propietarios que necesitan control y trabajadores que necesitan una interfaz clara.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-10">{features.map(F=><div key={F.title} className="p-6 rounded-2xl border border-slate-200"><div className="w-11 h-11 rounded-xl bg-violet-100 text-violet-700 flex items-center justify-center"><F.icon className="w-5 h-5"/></div><h3 className="font-black text-lg mt-5">{F.title}</h3><p className="text-sm text-slate-500 leading-6 mt-2">{F.text}</p></div>)}</div></div></section>
   <section id="planes" className="bg-[#F5F3FF]"><div className="max-w-7xl mx-auto px-5 sm:px-8 py-20"><div className="text-center max-w-2xl mx-auto"><p className="text-xs font-black uppercase tracking-[.2em] text-violet-600">Planes PALMYRA</p><h2 className="text-3xl sm:text-4xl font-black mt-3">Elige la capacidad que necesita tu negocio.</h2><p className="text-slate-600 mt-4">Precios de referencia en USD para la arquitectura internacional. En Cuba, por ahora, la contratación y el pago de los planes se gestionan en efectivo.</p></div><div className="grid lg:grid-cols-3 gap-5 mt-10 items-stretch">{plans.map((p,i)=><article key={p.name} className={i===1?"rounded-3xl bg-violet-700 text-white p-7 shadow-2xl":"rounded-3xl bg-white border border-violet-100 p-7 shadow-sm"}><div className="flex items-center justify-between gap-2"><span className="text-xs font-black uppercase tracking-widest">{p.name}</span><span className={(i===1?"bg-white/15 text-white":"bg-violet-100 text-violet-700")+" px-2.5 py-1 rounded-full text-[9px] font-black"}>{p.badge}</span></div><div className="mt-6 flex items-end gap-1"><span className="text-5xl font-black">{p.price}</span><span className={(i===1?"text-violet-200":"text-slate-400")+" text-sm mb-2"}>USD / mes</span></div><p className="text-xs mt-2 opacity-75">Pago internacional preparado · Cuba: efectivo</p><ul className="space-y-3 mt-7">{p.features.map(f=><li key={f} className="flex items-start gap-2 text-sm"><Check className={i===1?"text-violet-200":"text-emerald-600"} className="w-4 h-4 shrink-0 mt-0.5"/><span className={i===1?"text-white/90":"text-slate-600"}>{f}</span></li>)}</ul><button onClick={()=>navigate("/auth?mode=signup")} className={i===1?"w-full mt-8 h-11 rounded-xl bg-white text-violet-700 font-black":"w-full mt-8 h-11 rounded-xl bg-violet-600 text-white font-black"}>Comenzar <ChevronRight className="inline w-4 h-4"/></button></article>)}</div></div></section>
   <section id="como-funciona" className="bg-white"><div className="max-w-7xl mx-auto px-5 sm:px-8 py-20"><div className="text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-violet-600">Así funciona</p><h2 className="text-3xl sm:text-4xl font-black mt-3">De cero a operar en pocos pasos.</h2></div><div className="grid md:grid-cols-4 gap-4 mt-10">{[{n:"01",t:"Crea tu cuenta",d:"Una cuenta PALMYRA pertenece a una sola empresa."},{n:"02",t:"Crea tu empresa",d:"Elige el plan y crea tu almacén inicial."},{n:"03",t:"Invita a tu equipo",d:"Crea trabajadores, roles y permisos."},{n:"04",t:"Empieza a vender",d:"POS, inventario y operaciones incluso offline."}].map(s=><div key={s.n} className="p-6 rounded-2xl bg-[#FAF9FF] border border-violet-100"><span className="text-xs font-black text-violet-500">{s.n}</span><h3 className="font-black mt-4">{s.t}</h3><p className="text-sm text-slate-500 mt-2 leading-6">{s.d}</p></div>)}</div></div></section>
   <section className="bg-[#171128] text-white"><div className="max-w-5xl mx-auto px-5 sm:px-8 py-20 text-center"><div className="w-14 h-14 rounded-2xl bg-violet-600 mx-auto flex items-center justify-center"><PackageCheck className="w-7 h-7"/></div><h2 className="text-3xl sm:text-5xl font-black mt-6 tracking-tight">Haz que tu operación sea más simple.</h2><p className="text-violet-200 max-w-2xl mx-auto mt-4 leading-7">PALMYRA convierte las operaciones diarias de tu negocio en un sistema organizado, seguro y fácil de usar.</p><button onClick={()=>navigate("/auth?mode=signup")} className="mt-8 px-7 h-12 rounded-xl bg-white text-violet-700 font-black">Crear cuenta gratis <ArrowRight className="inline w-4 h-4 ml-1"/></button></div></section>
  </main>
  <footer className="bg-[#0F0B19] text-white/60"><div className="max-w-7xl mx-auto px-5 sm:px-8 py-10 flex flex-col md:flex-row gap-5 items-center justify-between"><div className="flex items-center gap-2 text-white"><span className="w-8 h-8 rounded-lg bg-violet-600 flex items-center justify-center"><Zap className="w-4 h-4"/></span><span className="font-black">PALMYRA</span></div><p className="text-xs">© 2026 PALMYRA. Gestión empresarial.</p><div className="flex gap-5 text-xs font-bold"><button onClick={()=>navigate("/auth")} className="hover:text-white">Acceder</button><a href="#planes" className="hover:text-white">Planes</a></div></div></footer>
 </div>
}