import React from 'react';
import { ArrowRight, BarChart3, Boxes, Check, ChevronDown, CloudOff, Menu, ShieldCheck, ShoppingCart, Sparkles, Store, Users, X, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PALMYRA_PLANS } from '../config/saas';

const featureCards = [
  { icon: ShoppingCart, title: 'Punto de venta', text: 'Vende rápido con una caja pensada para el ritmo de tu negocio.' },
  { icon: Boxes, title: 'Inventario por almacén', text: 'Controla existencias, mínimos y movimientos sin perder el hilo.' },
  { icon: BarChart3, title: 'Reportes de negocio', text: 'Entiende ventas, inventario y rendimiento desde un solo lugar.' },
  { icon: Users, title: 'Equipo y permisos', text: 'Administra empleados y accesos según las necesidades de tu empresa.' },
  { icon: CloudOff, title: 'Modo offline', text: 'Sigue operando cuando la conexión falle y sincroniza después.' },
  { icon: ShieldCheck, title: 'Arquitectura empresarial', text: 'Cada empresa trabaja con su propio espacio y datos aislados.' }
];

function Mockup({ type }: { type: 'dashboard' | 'pos' | 'inventory' }) {
  if (type === 'pos') return (
    <div className="rounded-[2rem] border border-white/70 bg-white p-4 shadow-2xl shadow-rose-200/50">
      <div className="flex items-center justify-between border-b border-slate-100 pb-3"><div><div className="text-[11px] font-extrabold text-slate-400">PALMYRA POS</div><div className="text-sm font-black text-slate-900">Nueva venta</div></div><div className="rounded-full bg-rose-50 px-3 py-1 text-xs font-bold text-rose-600">Caja abierta</div></div>
      <div className="grid grid-cols-[1.25fr_.75fr] gap-3 pt-3"><div className="grid grid-cols-2 gap-2">{['Café molido','Pan artesanal','Agua mineral','Detergente'].map((x,i)=><div key={x} className="rounded-xl bg-slate-50 p-3"><div className="mb-2 h-12 rounded-lg bg-gradient-to-br from-rose-50 to-pink-100" /><div className="text-xs font-bold text-slate-700">{x}</div><div className="mt-1 text-xs font-black text-rose-600">{'$'+[8,4,2,7][i]+'.00'}</div></div>)}</div><div className="rounded-2xl bg-slate-950 p-4 text-white"><div className="text-[10px] font-bold uppercase tracking-widest text-white/50">Resumen</div><div className="mt-4 space-y-2 text-xs text-white/70"><div className="flex justify-between"><span>4 productos</span><span>$21.00</span></div><div className="flex justify-between"><span>Impuestos</span><span>$1.68</span></div></div><div className="mt-6 border-t border-white/10 pt-4"><div className="text-[10px] uppercase text-white/50">Total</div><div className="text-3xl font-black">$22.68</div></div><div className="mt-5 rounded-xl bg-rose-500 py-3 text-center text-xs font-black">Cobrar ahora</div></div></div>
    </div>
  );
  if (type === 'inventory') return (
    <div className="rounded-[2rem] border border-white/70 bg-white p-4 shadow-2xl shadow-rose-200/50">
      <div className="flex items-center justify-between border-b border-slate-100 pb-3"><div><div className="text-[11px] font-extrabold text-slate-400">INVENTARIO</div><div className="text-sm font-black text-slate-900">Almacén principal</div></div><div className="rounded-xl bg-rose-50 px-3 py-2 text-xs font-bold text-rose-600">+ Producto</div></div>
      <div className="mt-3 space-y-2">{[['Café molido 500g','CAF-500','124','Normal'],['Pan artesanal','PAN-001','18','Bajo'],['Agua mineral 1.5L','AGU-15','260','Normal'],['Detergente líquido','DET-750','9','Crítico']].map(([name,sku,qty,status])=><div key={sku} className="grid grid-cols-[1fr_auto_auto] items-center gap-3 rounded-xl bg-slate-50 px-3 py-3"><div><div className="text-xs font-extrabold text-slate-800">{name}</div><div className="text-[10px] text-slate-400">{sku}</div></div><div className="text-sm font-black text-slate-800">{qty}</div><span className={status==='Normal'?'rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-600':status==='Bajo'?'rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-bold text-amber-600':'rounded-full bg-rose-50 px-2.5 py-1 text-[10px] font-bold text-rose-600'}>{status}</span></div>)}</div>
    </div>
  );
  return (
    <div className="rounded-[2rem] border border-white/70 bg-white p-4 shadow-2xl shadow-rose-200/50"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-slate-950 p-5 text-white"><div className="text-[10px] uppercase tracking-widest text-white/45">Ventas del mes</div><div className="mt-2 text-3xl font-black">$18,430</div><div className="mt-2 text-xs font-bold text-rose-300">+12.8% vs. mes anterior</div></div><div className="rounded-2xl bg-rose-50 p-5"><div className="text-[10px] uppercase tracking-widest text-rose-500/60">Productos</div><div className="mt-2 text-3xl font-black text-slate-900">128</div><div className="mt-2 text-xs font-bold text-rose-600">32 con movimiento hoy</div></div></div><div className="mt-3 rounded-2xl bg-slate-50 p-5"><div className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400">Rendimiento semanal</div><div className="mt-5 flex h-28 items-end gap-2">{[38,60,46,72,54,84,96].map((v,i)=><div key={i} className="flex-1 rounded-t-lg bg-gradient-to-t from-rose-500 to-pink-300" style={{height:v+'%'}} />)}</div></div></div>
  );
}

export default function Landing() {
  const [mobileMenu,setMobileMenu]=React.useState(false);
  const [openFaq,setOpenFaq]=React.useState<number|null>(0);
  return <div className="min-h-screen overflow-x-hidden bg-[#fff8fb] text-slate-900">
    <header className="sticky top-0 z-40 border-b border-rose-100 bg-white/90"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link to="/" className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-gradient-to-br from-rose-500 to-pink-500 text-white shadow-lg shadow-rose-200"><Store size={20}/></div><div><div className="text-lg font-black tracking-tight">PALMYRA POS</div><div className="text-[10px] font-bold uppercase tracking-[.25em] text-rose-500">Business SaaS</div></div></Link><nav className="hidden items-center gap-7 text-sm font-bold text-slate-600 md:flex"><a href="#funciones">Funciones</a><a href="#como-funciona">Cómo funciona</a><a href="#precios">Precios</a><a href="#faq">Preguntas</a></nav><div className="hidden items-center gap-3 md:flex"><Link to="/login" className="rounded-xl px-4 py-2.5 text-sm font-extrabold text-slate-700 hover:bg-rose-50">Iniciar sesión</Link><Link to="/signup" className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-extrabold text-white">Crear cuenta</Link></div><button className="md:hidden" onClick={()=>setMobileMenu(v=>!v)} aria-label="Abrir menú">{mobileMenu?<X/>:<Menu/>}</button></div>{mobileMenu&&<div className="border-t border-rose-100 bg-white px-5 py-4 md:hidden"><div className="grid gap-3 text-sm font-bold"><a href="#funciones">Funciones</a><a href="#precios">Precios</a><Link to="/login">Iniciar sesión</Link><Link to="/signup" className="rounded-xl bg-slate-950 px-4 py-3 text-center text-white">Crear cuenta</Link></div></div>}</header>
    <main>
      <section><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-16 lg:grid-cols-[.95fr_1.05fr] lg:px-8 lg:pb-28 lg:pt-24"><div><div className="inline-flex items-center gap-2 rounded-full border border-rose-200 bg-white px-3 py-1.5 text-xs font-extrabold text-rose-600"><Sparkles size={14}/> POS empresarial, simple de usar</div><h1 className="mt-6 max-w-3xl text-5xl font-black tracking-[-.05em] sm:text-6xl lg:text-7xl">Todo tu negocio.<br/><span className="bg-gradient-to-r from-rose-500 to-pink-500 bg-clip-text text-transparent">En un solo lugar.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">PALMYRA POS combina ventas, inventario, almacenes, clientes, reportes y equipo en una plataforma SaaS diseñada para empresas que quieren crecer con control.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/signup" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-rose-500 px-6 py-4 font-black text-white shadow-xl shadow-rose-200 hover:bg-rose-600">Empezar con PALMYRA <ArrowRight size={18}/></Link><a href="#funciones" className="inline-flex items-center justify-center rounded-2xl border border-slate-200 bg-white px-6 py-4 font-black text-slate-700">Ver funciones</a></div><div className="mt-8 grid max-w-xl grid-cols-3 gap-4 text-sm"><div><div className="font-black">Multi-almacén</div><div className="text-slate-500">Según tu plan</div></div><div><div className="font-black">Modo offline</div><div className="text-slate-500">Opera sin internet</div></div><div><div className="font-black">SaaS seguro</div><div className="text-slate-500">Datos por empresa</div></div></div></div><div><Mockup type="dashboard"/></div></div></section>
      <section id="funciones" className="border-y border-rose-100 bg-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="max-w-2xl"><div className="text-sm font-black uppercase tracking-[.18em] text-rose-500">Funciones</div><h2 className="mt-3 text-4xl font-black tracking-tight">La operación diaria, sin herramientas separadas.</h2><p className="mt-4 text-lg leading-8 text-slate-600">Desde la caja hasta los reportes, PALMYRA conecta la información que tu equipo necesita.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{featureCards.map(({icon:Icon,title,text})=><div key={title} className="rounded-3xl border border-slate-100 bg-[#fffafb] p-6 transition hover:-translate-y-1 hover:shadow-xl hover:shadow-rose-100"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-rose-100 text-rose-600"><Icon size={22}/></div><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>)}</div></div></section>
      <section className="bg-[#fff8fb]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><div className="text-sm font-black uppercase tracking-[.18em] text-rose-500">Capturas del producto</div><h2 className="mt-3 text-4xl font-black tracking-tight">Una interfaz que tu equipo entiende rápido.</h2><p className="mt-4 text-lg leading-8 text-slate-600">Diseñada para tablets, computadoras y el ritmo de una operación real.</p><div className="mt-8 space-y-4"><div className="flex gap-3"><div className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-rose-500 text-white"><Check size={15}/></div><div><div className="font-black">Caja rápida</div><div className="text-sm text-slate-600">Menos pasos para encontrar productos y cobrar.</div></div></div><div className="flex gap-3"><div className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-rose-500 text-white"><Check size={15}/></div><div><div className="font-black">Inventario por almacén</div><div className="text-sm text-slate-600">Cada almacén con su propia existencia y movimientos.</div></div></div><div className="flex gap-3"><div className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-rose-500 text-white"><Check size={15}/></div><div><div className="font-black">Reportes accionables</div><div className="text-sm text-slate-600">Información para decisiones operativas.</div></div></div></div></div><div><Mockup type="pos"/><div className="mt-4"><Mockup type="inventory"/></div></div></div></div></section>
      <section id="como-funciona" className="bg-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="text-center"><div className="text-sm font-black uppercase tracking-[.18em] text-rose-500">Cómo funciona</div><h2 className="mt-3 text-4xl font-black tracking-tight">Tu empresa lista en pocos pasos.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-4">{[['01','Crea tu cuenta','Registra tu nombre, correo y contraseña.'],['02','Crea tu empresa','Define el nombre de tu negocio y el plan.'],['03','Agrega operación','Crea tu primer almacén y empleado.'],['04','Empieza a vender','Entra al POS y configura el resto cuando quieras.']].map(([n,t,d])=><div key={n} className="rounded-3xl border border-slate-100 bg-[#fffafb] p-6"><div className="text-4xl font-black text-rose-200">{n}</div><h3 className="mt-3 text-lg font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></div>)}</div></div></section>
      <section id="precios" className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="text-sm font-black uppercase tracking-[.18em] text-rose-300">Precios</div><h2 className="mt-3 text-4xl font-black tracking-tight">Empieza con el tamaño que necesitas.</h2></div><p className="max-w-xl text-sm leading-6 text-white/60">Los límites de productos son por tipos de producto/SKUs, no por cantidad de unidades físicas.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{PALMYRA_PLANS.map(plan=><div key={plan.code} className={plan.code==='growth'?'rounded-[2rem] border border-rose-400 bg-white p-7 text-slate-900 shadow-2xl':'rounded-[2rem] border border-white/10 bg-white/5 p-7'}><div className="flex items-center justify-between"><div className="text-lg font-black">{plan.name}</div>{plan.code==='growth'&&<span className="rounded-full bg-rose-100 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-rose-600">Popular</span>}</div><div className="mt-5 flex items-end gap-1"><span className="text-5xl font-black">{'$'+plan.price}</span><span className="pb-2 text-sm opacity-60">/mes</span></div><p className="mt-3 text-sm leading-6 opacity-70">{plan.description}</p><div className="mt-6 space-y-3">{plan.features.map(f=><div key={f} className="flex gap-2 text-sm"><Check size={16} className={plan.code==='growth'?'text-rose-500':'text-rose-300'}/><span>{f}</span></div>)}</div><Link to={'/signup?plan='+plan.code} className={plan.code==='growth'?'mt-8 flex items-center justify-center gap-2 rounded-2xl bg-rose-500 px-4 py-3.5 text-sm font-black text-white':'mt-8 flex items-center justify-center gap-2 rounded-2xl bg-white px-4 py-3.5 text-sm font-black text-slate-950'}>Elegir {plan.name}<ArrowRight size={16}/></Link></div>)}</div></div></section>
      <section id="faq" className="bg-[#fff8fb]"><div className="mx-auto max-w-4xl px-5 py-20 lg:px-8"><div className="text-center"><div className="text-sm font-black uppercase tracking-[.18em] text-rose-500">FAQ</div><h2 className="mt-3 text-4xl font-black tracking-tight">Preguntas frecuentes</h2></div><div className="mt-10 space-y-3">{[['¿El límite de productos cuenta las unidades en inventario?','No. Cuenta el número de tipos de productos/SKUs que registra la empresa.'],['¿Puedo manejar varios almacenes?','Sí. El máximo depende del plan.'],['¿Puedo vender sin internet?','PALMYRA está orientado a una operación offline-first y sincroniza cuando la conexión vuelve.'],['¿Puedo cambiar de plan?','La arquitectura SaaS incluye selección y cambio de plan con validación de límites.']].map(([q,a],i)=><button key={q} onClick={()=>setOpenFaq(openFaq===i?null:i)} className="w-full rounded-2xl border border-rose-100 bg-white p-5 text-left"><div className="flex items-center justify-between gap-5"><span className="font-black">{q}</span><ChevronDown size={18} className={openFaq===i?'rotate-180 text-rose-500':''}/></div>{openFaq===i&&<p className="mt-3 pr-8 text-sm leading-6 text-slate-600">{a}</p>}</button>)}</div></div></section>
      <section className="bg-rose-500"><div className="mx-auto max-w-6xl px-5 py-14 text-center lg:px-8"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-white/15 text-white"><Zap/></div><h2 className="mt-5 text-4xl font-black tracking-tight text-white">Haz que tu operación se sienta más simple.</h2><p className="mx-auto mt-3 max-w-2xl text-base leading-7 text-white/85">Crea tu cuenta, configura tu empresa y lleva tu negocio a PALMYRA POS.</p><Link to="/signup" className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-4 font-black text-rose-600">Crear mi cuenta <ArrowRight size={18}/></Link></div></section>
    </main>
    <footer className="bg-slate-950 text-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><div className="font-black">PALMYRA POS</div><div className="mt-1 text-white/40">Gestión empresarial para negocios que quieren crecer.</div></div><div className="text-white/40">© {new Date().getFullYear()} PALMYRA POS</div></div></footer>
  </div>;
};
