// Generated from the current product catalog. Acceleration dictionary only.
// IDs, prices and stock always come from the live/local product store.
export const KNOWN_PRODUCT_NAMES = [
  "Air max Sin Hacer",
  "Alarmas",
  "Amiris Hombre",
  "Anillos Shein",
  "Aretes",
  "Aretes 600 cup",
  "Aretes Shein",
  "Bisutería 1250 cup",
  "Blusas 3700 cup",
  "Blusas 7100 cup",
  "Blusas Baratas Niña",
  "Blusas Finas Niña",
  "Blusas Mary",
  "Bocina 2401",
  "Bocina 8810",
  "Bocina 8817",
  "Bocina 8847",
  "Bolígrafos 250 cup",
  "Bolígrafos 90 cup",
  "Bolso Labubu Silicona",
  "Bolsos Maternidad",
  "Bolsos Stitch",
  "Cadenas",
  "Calculadoras Científicas",
  "Camisetas Girasol",
  "Carteras Fashion",
  "Carteras Sprayground",
  "Cepillos Dientes",
  "Chancleta K-pop Niña",
  "Chancleta Marca",
  "Chancletas Chinas",
  "Chancletas Dofimall",
  "Chaquetas Mezclilla",
  "Cintas Métricas",
  "Cintillos",
  "Cocina Electrica",
  "Conjuntos Baratos Niños",
  "Conjuntos Caros Niños",
  "Conjuntos Dominicana 12 400 cup",
  "Conjuntos Mujer - Vestidos 10 800 cup",
  "Conjuntos Tongo Cortos",
  "Conjuntos Tongo Largos",
  "Cortauñas",
  "Cortinas",
  "Creyones Matte",
  "Cuchillas de Afeitar",
  "Desodorantes Rexona",
  "Dijes",
  "Encendedores Eléctricos",
  "Esponjas Baño",
  "Estante",
  "Estuche Peines Vero",
  "Felpita - pellizquito",
  "Felpita Labubu",
  "Hebillas 700",
  "Hilos Dentales",
  "Jeringuillas Insulina",
  "Jogger Hombre",
  "Jogger Niño",
  "Kit Manicura Annia",
  "Kit Manicura Cris",
  "Kit Manicura Vero",
  "Lámparas 18w",
  "Lámparas solares",
  "Lazo  Pelo",
  "Licras Largas",
  "Licras Levanta Glúteos",
  "Llaveros",
  "Llaveros con Pelo",
  "Llaveros Labubu",
  "Mandos Universales",
  "Manillas",
  "Marcadores Negros",
  "Mechas",
  "Medias Adidas Annia",
  "Medias Adidas Cris",
  "Mochilas 12 000 cup Annia",
  "Mochilas 12 000 cup Cris",
  "Mochilas 14 000 cup Annia",
  "Mochilas 14 000 cup Cris",
  "Mochilas 16 000 Annia",
  "Mochilas 16 000 Cris",
  "Mochilas 7300 Cris",
  "Mochilas 9300 cup Annia",
  "Mochilas 9300 CUP Cris",
  "Mochilas Chinas Annia",
  "Mochilas Chinas Cris",
  "Mochilas Chinas Vero",
  "Mochilas Niños",
  "Monederos",
  "Morrales de Hombre",
  "Mosquiteros",
  "Pandoras",
  "Pantalón Mezclilla Mujer",
  "Pantalón Tela De Niña",
  "Paquetes Caramelos",
  "Paquetes Medias",
  "Paraguas",
  "Pegamento De Uña",
  "Pegamentos",
  "Peine Grande",
  "Peine Piojos",
  "Pelador papa",
  "Pellizcos 1000",
  "Pellizcos 1050",
  "Pellizcos Triples",
  "Peluches",
  "Perfiladores Cejas",
  "Perfumes",
  "Pescador Mezclilla Niños",
  "Pescador Mezclilla Perlas",
  "Pijamas Stitch",
  "Pintalabios Labubu",
  "Pintalabios Matte",
  "Pinzas Cejas",
  "Pinzas Cejas Triples",
  "Plantillas",
  "Pomos 1700",
  "Pompones",
  "Prácticas Mujer",
  "Prácticas Niños",
  "Protectores de Teléfono",
  "Pullover Barato Hombre",
  "Pullover Cajón 4500 cup",
  "Pullover Cajón 5700 cup",
  "Pullover Caro Hombre",
  "Pullover Caro Niño",
  "Pullover Niños 3350 cup",
  "Pullover Palm Angel Mujer",
  "Pulsos Shein",
  "Pumas Hombre Merma",
  "Riñonera Hombre",
  "Saca Granos",
  "Sandalias",
  "Sazones Goya",
  "Set Cuchillos",
  "Set Esponjas",
  "Set Silicona",
  "Short Ancla Hombre",
  "Short Ancla Niño",
  "Short Doble Hombre",
  "Short Mezclilla Mujer CD",
  "Short Mezclilla Mujer SD",
  "Short Mezclilla Niña",
  "Short Palm Angel Mujer",
  "Suecos",
  "Tapetes de Baño",
  "Tapetes Disney",
  "Tenis 11 700 cup",
  "Tenis 13 300 cup",
  "Tenis 14 800 cup",
  "Tenis 15 500 cup",
  "Tenis 16 000 cup",
  "Tenis 17 400 cup",
  "Tenis 18 000 cup",
  "Tenis 18 500 cup",
  "Tenis 19 200 cup",
  "Tenis 6400 cup",
  "Tenis 7650 cup Annia",
  "Tenis 7650 cup Vero",
  "Tenis 7800 cup",
  "Tenis 8450 cup",
  "Tenis 9300",
  "Termómetros",
  "Test Embarazo",
  "Toallitas Niños",
  "Vasos Shot",
  "Ventilador X13",
  "Ventiladores f6",
  "Vestidos Girasol",
  "Vestidos Olinda",
  "Vestidos Reeb"
] as const;

export const KNOWN_PRODUCT_NAMES_NORMALIZED = new Set(KNOWN_PRODUCT_NAMES.map(name =>
  name.normalize("NFD").replace(/[\\u0300-\\u036f]/g, "").toLowerCase().replace(/\\s+/g, " ").trim()
));
